require_relative '../../node_modules/@capacitor/ios/scripts/pods_helpers'

platform :ios, '14.0'
use_frameworks!

# workaround to avoid Xcode caching of Pods that requires
# Product -> Clean Build Folder after new Cordova plugins installed
# Requires CocoaPods 1.6 or newer
install! 'cocoapods', :disable_input_output_paths => true

def capacitor_pods
  pod 'Capacitor', :path => '../../node_modules/@capacitor/ios'
  pod 'CapacitorCordova', :path => '../../node_modules/@capacitor/ios'

end

target 'App' do
  capacitor_pods
  # 內嵌 HTTP server：以 http://localhost 服務網頁，設 COOP/COEP 讓頁面
  # cross-origin isolated（SharedArrayBuffer 可用），多執行緒引擎才能在 iOS 跑。
  pod 'GCDWebServer', '~> 3.0'
end

post_install do |installer|
  assertDeploymentTarget(installer)
end
